on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Repeat Backfill
      uses: bcanseco/github-contribution-graph-action@v2
      with:
        run_times: 5 # Tentukan berapa kali kamu ingin mengulangi proses backfill
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: jime.lkosongepep@gmail.com # replace me
        MAX_DAYS: 200
        MIN_COMMITS_PER_DAY: 1
        MAX_COMMITS_PER_DAY: 1
